models:
  - name: llama3
    label: LLaMA 3 8B
    prompt: "What is the capital of France?"

  - name: qwen:1.5b
    label: Qwen 1.5B
    prompt: "What is the capital of France?"

  - name: gemma:2b
    label: Gemma 2B
    prompt: "What is the capital of France?"
